DROP TABLE IF EXISTS userr;

CREATE TABLE userr (
	username VARCHAR(100) PRIMARY KEY NOT NULL,
	password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS role;

CREATE TABLE role (
	roleid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	rolename VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS usertorole;

CREATE TABLE usertorole (
	usertoroleid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	username VARCHAR(100) NOT NULL,
	roleid INT NOT NULL
);

DROP TABLE IF EXISTS privilege;

CREATE TABLE privilege (
	privilegeid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	privilegename VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS roletoprivilege;

CREATE TABLE roletoprivilege (
	roletoprivilegeid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	roleid INT NOT NULL,
	privilegeid INT NOT NULL
);

ALTER TABLE usertorole DROP CONSTRAINT IF EXISTS userr_usertorole;
ALTER TABLE usertorole ADD CONSTRAINT userr_usertorole FOREIGN KEY (username) REFERENCES userr(username);

ALTER TABLE usertorole DROP CONSTRAINT IF EXISTS role_usertorole;
ALTER TABLE usertorole ADD CONSTRAINT role_usertorole FOREIGN KEY (roleid) REFERENCES role(roleid);

ALTER TABLE roletoprivilege DROP CONSTRAINT IF EXISTS privilege_roletoprivilege;
ALTER TABLE roletoprivilege ADD CONSTRAINT privilege_roletoprivilege FOREIGN KEY (privilegeid) REFERENCES privilege(privilegeid);

ALTER TABLE roletoprivilege DROP CONSTRAINT IF EXISTS role_roletoprivilege;
ALTER TABLE roletoprivilege ADD CONSTRAINT role_roletoprivilege FOREIGN KEY (roleid) REFERENCES role(roleid);